[mypy]
python_version = 3.14
follow_imports = skip
check_untyped_defs = True
disallow_untyped_defs = True
files = tests/challenges/**/*.py
warn_unused_ignores = True
pretty = True

[mypy-requests.*]
ignore_missing_imports = True
[mypy-yaml.*]
ignore_missing_imports = True
